---
namespace: amazon
name: ai
version: 1.0.0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: Ansible Collection for Amazon AI and ML Resources
license_file: LICENSE
tags:
  - ai
  - amazon
dependencies:
  amazon.aws: '>=10.0.0'
  community.aws: '>=10.0.0'
repository: https://github.com/ansible
homepage: https://github.com/ansible
issues: https://access.redhat.com/support/
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - '*cloud-config-aws.ini'
  - '*cloud-config-aws.yml'
